# Generated by Django 4.2 on 2023-04-10 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='grocery',
            table='grocery',
        ),
    ]
