# Generated by Django 4.2 on 2023-04-11 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery', '0003_merchant'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='merchant',
            table='merchant',
        ),
    ]
