# Generated by Django 4.2 on 2023-04-11 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery', '0004_alter_merchant_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='merchant',
            table='Merchant',
        ),
    ]
