# Generated by Django 4.2 on 2023-04-12 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery', '0005_alter_merchant_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=20)),
                ('discount', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='products')),
                ('Merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grocery.merchant')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
