# Generated by Django 4.2 on 2023-04-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery', '0007_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(max_length=20),
        ),
    ]
