# Generated by Django 4.2 on 2023-04-15 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery', '0009_alter_products_discount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grocery',
            new_name='Category',
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
