# Generated by Django 4.2 on 2023-04-17 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery', '0010_rename_grocery_category_alter_category_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'products'},
        ),
    ]
