# Generated by Django 4.2 on 2023-04-19 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery', '0011_alter_category_options_alter_products_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Grocery.category'),
            preserve_default=False,
        ),
    ]
