# Generated by Django 4.2 on 2023-04-19 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery', '0012_products_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='category_id',
            new_name='category',
        ),
    ]
